# Generated by Django 5.1.3 on 2024-12-02 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_code', models.CharField(max_length=20, unique=True)),
                ('course_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=25, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('Instructor', 'Instructor'), ('Teaching Assistant', 'Teaching Assistant'), ('Supervisor', 'Supervisor')], max_length=20)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('lab_id', models.AutoField(primary_key=True, serialize=False)),
                ('section_number', models.CharField(max_length=25)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labs', to='scheduler.course')),
                ('ta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labs_as_ta', to='scheduler.user')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_as_instructor', to='scheduler.user'),
        ),
    ]