# Generated by Django 5.1.2 on 2024-12-12 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='course',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='ta',
        ),
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='scheduler.course')),
                ('lab_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='scheduler.lab')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='scheduler.user')),
            ],
        ),
    ]
