# Generated by Django 5.1.3 on 2024-12-19 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_remove_lab_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labs', to='scheduler.course'),
        ),
    ]
