# Generated by Django 5.1.3 on 2024-12-16 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_remove_course_instructor_remove_lab_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses_as_instructor', to='scheduler.user'),
        ),
        migrations.AddField(
            model_name='lab',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labs', to='scheduler.course'),
        ),
        migrations.AddField(
            model_name='lab',
            name='ta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labs_as_ta', to='scheduler.user'),
        ),
    ]
