# Generated by Django 5.1.3 on 2024-12-18 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_course_instructor_lab_course_lab_ta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='ta',
        ),
        migrations.AlterField(
            model_name='lab',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='labs', to='scheduler.course'),
            preserve_default=False,
        ),
    ]
